### ISSUE TITLE
关于2V_MNIST_USPS.mat数据集

### ISSUE THREAD

**Issue by zhangyuanyang21** [SubmissionsIn/DEMVC#3]
你好！！请问2V_MNIST_USPS.mat数据集是怎么构成的？是mnist数据集和usps数据集合成的一个数据集吗？

**Comment by SubmissionsIn** [comment]
是的，MNIST和USPS分别作为两个view。

**Comment by zhangyuanyang21** [comment]
感谢您！在百忙之中回答我的问题，阅读您的论文和代码对我的研究方向受益匪浅，因为资质浅薄，在对您的论文和代码的阅读过程中存在一些困惑，希望您能多多指教！

**Comment by zhangyuanyang21** [comment]
dict_keys(['__header__', '__version__', '__globals__', 'X1', 'X2', 'Y'])，你好！请问数据集中的X1,X2,Y分别代表什么呢？为什么输出X1的矩阵里的数值全为0呢？X1和X2表示的分别是一个视图和第二个视图的节点N和特征F构成的矩阵吗？Y表示的是类别标签吗？请问2V_MNIST_USPS.mat数据集内部具体是什么结构呢？

**Comment by SubmissionsIn** [comment]
输出值为0是因为图片边缘的像素值为0，用print不能查看整个样本，可以尝试用Matplotlib可视化

**Comment by zhangyuanyang21** [comment]
非常感谢您，请问具体怎么用Matplotlib可视化数据集呢？您当时在构建该数据集的时候是怎么构建的呢？怎么查看数据数据集里的内容呢？

**Comment by zhangyuanyang21** [comment]
我想对您的多视图聚类方法非常感兴趣，想进一步优化多视图聚类，还请您多多指教

**Comment by zhangyuanyang21** [comment]
我对您的多视图聚类方法非常感兴趣，想进行一步的优化，还请您多多指教

**Comment by zhangyuanyang21** [comment]
您好！请问2V_MNIST_USPS.mat数据集里的X1：5000x28x28x1，5000是样本个数，28x28x1表示什么意思呢？Y：1x5000表示样本的真实标签

**Comment by SubmissionsIn** [comment]
28x28x1代表一个数字是28x28的单通道灰度图像

**Comment by zhangyuanyang21** [comment]
感谢您的回复！
您好！请问您有包含数据集中样本之间的关系的数据集吗？

**Comment by zhangyuanyang21** [comment]
您好，请问28x28是样本的维度吗？想问一下样本的维度是多少？

**Comment by zhangyuanyang21** [comment]
你好，请问怎么由2V_MNIST_USPS.mat数据集（样本属性数据集）构建出样本之间关系的数据集呢？

**Comment by SubmissionsIn** [comment]
不是很明白构建样本之间关系是什么意思。比如第一个实例，MNIST的第一个样本是第一个视图，USPS的第一个样本是另一个视图，它们的标签都是Y里面的第一个

**Comment by zhangyuanyang21** [comment]
谢谢您的回复！不好意思啊，问题有点多，希望您不要介意哈，
请问您构建的网络模型确实都经过以的下各层吗？并不是只有两个全连接层
Model: "model_6"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
input1 (InputLayer)             [(None, 28, 28, 1)]  0
__________________________________________________________________________________________________
input2 (InputLayer)             [(None, 28, 28, 1)]  0
__________________________________________________________________________________________________
conv1_v1 (Conv2D)               (None, 14, 14, 32)   832         input1[0][0]
__________________________________________________________________________________________________
conv1_v2 (Conv2D)               (None, 14, 14, 32)   832         input2[0][0]
__________________________________________________________________________________________________
conv2_v1 (Conv2D)               (None, 7, 7, 64)     51264       conv1_v1[0][0]
__________________________________________________________________________________________________
conv2_v2 (Conv2D)               (None, 7, 7, 64)     51264       conv1_v2[0][0]
__________________________________________________________________________________________________
conv3_v1 (Conv2D)               (None, 3, 3, 128)    73856       conv2_v1[0][0]
__________________________________________________________________________________________________
conv3_v2 (Conv2D)               (None, 3, 3, 128)    73856       conv2_v2[0][0]
__________________________________________________________________________________________________
Flatten1 (Flatten)              (None, 1152)         0           conv3_v1[0][0]
__________________________________________________________________________________________________
Flatten2 (Flatten)              (None, 1152)         0           conv3_v2[0][0]
__________________________________________________________________________________________________
embedding1 (Dense)              (None, 10)           11530       Flatten1[0][0]
__________________________________________________________________________________________________
embedding2 (Dense)              (None, 10)           11530       Flatten2[0][0]
__________________________________________________________________________________________________
Dense1 (Dense)                  (None, 1152)         12672       embedding1[0][0]
__________________________________________________________________________________________________
Dense2 (Dense)                  (None, 1152)         12672       embedding2[0][0]
__________________________________________________________________________________________________
Reshape1 (Reshape)              (None, 3, 3, 128)    0           Dense1[0][0]
__________________________________________________________________________________________________
Reshape2 (Reshape)              (None, 3, 3, 128)    0           Dense2[0][0]
__________________________________________________________________________________________________
deconv3_v1 (Conv2DTranspose)    (None, 7, 7, 64)     73792       Reshape1[0][0]
__________________________________________________________________________________________________
deconv3_v2 (Conv2DTranspose)    (None, 7, 7, 64)     73792       Reshape2[0][0]
__________________________________________________________________________________________________
deconv2_v1 (Conv2DTranspose)    (None, 14, 14, 32)   51232       deconv3_v1[0][0]
__________________________________________________________________________________________________
deconv2_v2 (Conv2DTranspose)    (None, 14, 14, 32)   51232       deconv3_v2[0][0]
__________________________________________________________________________________________________
clustering1 (ClusteringLayer)   (None, 10)           100         embedding1[0][0]
__________________________________________________________________________________________________
deconv1_v1 (Conv2DTranspose)    (None, 28, 28, 1)    801         deconv2_v1[0][0]
__________________________________________________________________________________________________
clustering2 (ClusteringLayer)   (None, 10)           100         embedding2[0][0]
__________________________________________________________________________________________________
deconv1_v2 (Conv2DTranspose)    (None, 28, 28, 1)    801         deconv2_v2[0][0]
==================================================================================================
Total params: 552,158
Trainable params: 552,158
Non-trainable params: 0

**Comment by SubmissionsIn** [comment]
不明白您说的两个全连接层是什么。这个代码只是论文的一种实现，您需要的细节或许可以在文中找到。

**Comment by zhangyuanyang21** [comment]
谢谢您的回复，
