### ISSUE TITLE
关于typenet = 'f-f'          # Fully connected networks 全连接网络

### ISSUE THREAD

**Issue by zhangyuanyang21** [SubmissionsIn/DEMVC#4]
您好，请问不用 卷积网络 训练，用全连接网络来训练需要修改哪些参数呢？

**Comment by zhangyuanyang21** [comment]
已经通过修改
# print(len(view_shape[0]))
    #修改此处的长度
    if len(view_shape[0]) == 3:
    # if len(view_shape[0]) == 1:
        typenet = 'f-f'          # Fully connected networks
    else:
        typenet = 'c-c'          # Convolution networks
将网络类型变成了全连接类型，但是运行代码出现报错
    ValueError: Input 0 of layer v2_encoder_0 is incompatible with the layer: expected axis -1 of input shape to have value 28 but received input with shape (None, 28, 28, 1)
请问这个问题怎么解决呢？

**Comment by zhangyuanyang21** [comment]
> 
data = 'MNIST_USPS_COMIC'     
  # the tested datasets contain:
  # 'MNIST_USPS_COMIC'        (CAE)
  # 'BDGP'                    (FAE)
噢噢明白了要改数据集，把数据集改成BDGP，但是您提供了MNIST_USPS数据集，您好！可以提供一下BDGP的数据集吗，麻烦您了！

**Comment by zhangyuanyang21** [comment]
您好！可以帮我看下这个问题吗？麻烦您了！

**Comment by SubmissionsIn** [comment]
The old version has a txt that provides the datasets.

**Comment by zhangyuanyang21** [comment]
thanks you very much
