### ISSUE TITLE
codes function

### ISSUE THREAD

**Issue by zhangyuanyang21** [SubmissionsIn/DEMVC#6]
Hello! I would like to ask what the following codes do?

   if y is not None and verbose > 0:
            class PrintACC(callbacks.Callback):
                def __init__(self, x, y, flag=1):
                    self.x = x
                    self.y = y
                    self.flag = flag
                    super(PrintACC, self).__init__()

                def on_epoch_end(self, epoch, logs=None):
                    time = 1    #  show k-means results on z
                    if int(epochs / time) != 0 and (epoch+1) % int(epochs/time) != 0:
                        # print(epoch)
                        return
                    view_name = 'embedding' + str(self.flag)
                    feature_model = Model(self.model.input[self.flag - 1],
                                              self.model.get_layer(name=view_name).output)
                    
                    features = feature_model.predict(self.x)
                    km = KMeans(n_clusters=len(np.unique(self.y)), n_init=20, n_jobs=4)
                    y_pred = km.fit_predict(features)
                    print('\n' + ' '*8 + '|==>  acc: %.4f,  nmi: %.4f  <==|'
                          % (Nmetrics.acc(self.y, y_pred), Nmetrics.nmi(self.y, y_pred)))

            for view in range(len(x)):
                cb.append(PrintACC(x[view], y, flag=view + 1))

**Comment by SubmissionsIn** [comment]
Print ACC during pre-training

**Comment by zhangyuanyang21** [comment]
Hello ! What is the role of pre-training? 预训练的作用是什么呢

**Comment by zhangyuanyang21** [comment]
> 
评估的标准不止ACC 还有nmi ， ARI 等等 为什么只打印ACC呢

**Comment by SubmissionsIn** [comment]
这个只是测试一下而已，print('\n' + ' '*8 + '|==>  acc: %.4f,  nmi: %.4f  <==|'

**Comment by zhangyuanyang21** [comment]
预训练的作用是什么呢

**Comment by SubmissionsIn** [comment]
预训练后做k-means才有意义

**Comment by zhangyuanyang21** [comment]
您好！在代码的聚类部分每个视图都会轮流成为其他视图的参考视图，我想请问您这部分代码怎么用pytorch实现呢？麻烦您了！
