### ISSUE TITLE
使用pytorch复现论文时候出现的问题

### ISSUE THREAD

**Issue by zhangyuanyang21** [SubmissionsIn/DEMVC#8]
你好！我在使用pytorch复现论文的时候发现实验结果acc最高只能达到0.5 ，nmi最高能达到0.6，和论文里的实验结果acc ，nmi ， ari   =  99.83 ，99.49， 99.63， 差距非常大，请问是什么原因呢？

**Comment by zhangyuanyang21** [comment]
您好，我复现的方式是将原代码里的数据集移植到一个pytorch的单视图DNN的框架里进行训练，训练过程中将数据集里的两个视图x1和x2分别输入到DNN里训练，聚类后得到分布q和分布p后再进行参考视图的部分 ，即将依次将p和各个q进行kl 之后在求和

**Comment by zhangyuanyang21** [comment]
你好！请问多视图协同训练部分的代码在什么位置？代码中多视图训练的时候先是分别将两个视图输入到编码器中训练，然后再用协同训练达到互补性，最后在用kmeans方法聚类吗？

**Comment by zhangyuanyang21** [comment]
非常抱歉，向您请教了太多的问题，给您带来了麻烦，不好意思！   
  
祝您生活愉快，工作顺利！

**Comment by SubmissionsIn** [comment]
可否直接通过邮件跟我联系？

**Comment by zhangyuanyang21** [comment]
当然，可以，请问您邮件地址多少？

**Comment by zhangyuanyang21** [comment]
我的邮箱地址是 yuanyangzhang2021@163.com
